### ISSUE TITLE
Consider changing IonType from an enum to a class

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-dotnet#13]
[IonType](https://github.com/amzn/ion-dotnet/blob/master/IonDotnet/IonType.cs) is currently implemented as an enum--effectively named ints:
* the current ints align with the Ion binary type codes for Null, Bool, and Int, but all the others are off by one--I can imagine this leading to bugs, or at least some confusion
* `IonType.None` (-1) exists to represent the `null` case
* I suspect the compiler sees a value of 12345 as a valid IonType as well

I'd suggest we consider defining IonType using a class instead, aiming for the same API, ints that align with the Ion binary type codes, and stronger compile-time checks.

**Comment by tgregg** [comment]
Taking a look at #29, it's hard for me to see how making IonType a class is an improvement over keeping it as an enum and just aligning the values with the binary type codes. It seems to make working with IonType more verbose.

@pbcornell Can you expand on the advantages of this approach?

**Comment by pbcornell** [comment]
Hmm...the advantages seem to have evaporated as I look at #29 and experiment a bit.  Specifically:
* The compiler appears to treat enums as more than just a int, and _does_ perform compile-time checks--cool
* C# switch statements require each case to be a compile-time constant, so using a class-based enum in a switch statement is messy and verbose

The ability to use `null` instead of `IonType.None` is a personal preference, and a trivial one at that.

> Can you expand on the advantages of this approach?

I appreciate that we've considered the idea, but I don't see any real advantages at this time and can't recommend proceeding with it.

That said, aligning the values with the binary type codes as you've suggested would likely be helpful for the ion-hash-dotnet project, and perhaps generally.
