### ISSUE TITLE
Determine whether the tests implement embedded_documents semantics

### ISSUE THREAD

**Issue by tgregg** [amzn/ion-dotnet#2]
From the [ion-tests](https://github.com/amzn/ion-tests) Readme:

> If a top-level sequence is annotated with "embedded_documents", it denotes that each of its Ion values is to be parsed as a Ion string value, where its string value is to be parsed as a document. As such, each top-level sequence contains at least two documents, all of which should be equivalent or non-equivalent within the Ion data model, for the directories good/equivs and good/non-equivs respectively.

Implementing this involves creating a new reader for each string and verifying that each reader produces a data model-equivalent Ion stream.

**Comment by Armanbqt** [comment]
For both good/equivs and good/non-equivs, if the test contains "embedded_documents" annotation, each value of the IonSequence should be IonString ([here](https://github.com/amzn/ion-dotnet/blob/master/IonDotnet.Tests/Integration/Vector.cs#L223))
Next, the test gets the next IonString of the sequence and using these 2 IonStrings, loads their respective IonDatagrams([here](https://github.com/amzn/ion-dotnet/blob/master/IonDotnet.Tests/Integration/Vector.cs#L224) and [here](https://github.com/amzn/ion-dotnet/blob/master/IonDotnet.Tests/Integration/Vector.cs#L232))
And finally a comparison to verify if both are equal ([here](https://github.com/amzn/ion-dotnet/blob/master/IonDotnet.Tests/Integration/Vector.cs#L233)).
