### ISSUE TITLE
Add .build(IonValue ionValue) to IonReaderBuilder

### ISSUE THREAD

**Issue by simonz-bq** [amzn/ion-dotnet#28]
We need the ability to create an IonReader with an IonValue, as this functionality is used for Hashing and is available in the Java and JS implementations

**Comment by pbcornell** [comment]
Instead of adding `.withValue()`, I'd suggest continuing the existing IonReaderBuilder pattern by overloading `.Build()`.

**Comment by tgregg** [comment]
Fixed in #51
