### ISSUE TITLE
IonType Int enum only corresponds to binary Ion type code 2 

### ISSUE THREAD

**Issue by byronlin-bq** [amzn/ion-dotnet#41]
Currently IonType.Int only returns 2

If there is a negative int in the ion value, it will not match.

[https://github.com/amzn/ion-dotnet/commit/910ca7fe7e8f84f9e5fc5c9ee07f8483abff1acb](url)

**Comment by tgregg** [comment]
This shouldn't be a problem. Making the IonType enum values basically align with the binary type code tends to reduce confusion, but in the case of the `int` type, the binary type code cannot be mapped directly to the enum value. Negative `int` values (type code 3) should still map to IonType.Int (which has the value 2).
