### ISSUE TITLE
Use type code in BinaryConstants.cs instead of IonType.cs

### ISSUE THREAD

**Issue by byronlin-bq** [amzn/ion-dotnet#42]
We should use the type codes in [BinaryConstants.cs](https://github.com/amzn/ion-dotnet/blob/master/IonDotnet/Internals/Binary/BinaryConstants.cs#L14) instead of the [IonType](https://github.com/amzn/ion-dotnet/blob/master/IonDotnet/IonType.cs#L5) enum. The IonType enum is missing type code for negative int.

**Comment by tgregg** [comment]
In places where a binary type code is needed, use BinaryConstants. All other places can use IonType. IonType is public, while BinaryConstants is not because the user does not need to care about binary type codes.

**Comment by Armanbqt** [comment]
@tgregg , since this issue will not change any functionality/behaviour and is more of an internal refactoring, can we change the milestone to GA?

**Comment by tgregg** [comment]
Closed via #76
