### ISSUE TITLE
Add more convenient method(s) to IIonReader for determining whether an annotation is present

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-dotnet#68]
The `IIonReader` interface currently provides:
```C#
IEnumerable<SymbolToken> GetTypeAnnotations()
```
which isn't particularly convenient when checking to see if a specific annotation is present.  Also note that ion-java's equivalent of this method is called `getTypeAnnotationSymbols()`.

Something like `string[] GetTypeAnnotations()` or `bool HasAnnotation(string annotation)` would be more helpful.

**Comment by tgregg** [comment]
Once this is added, use it in the Sparse Reads example in the cookbook, replacing the inline implementation that is currently there.

**Comment by pbcornell** [comment]
To clarify, I propose the following changes to the `IIonReader` interface:
* rename the existing `GetTypeAnnotations()` method to `GetTypeAnnotationSymbols()`
* add `string[] GetTypeAnnotations()`
* add `bool HasAnnotation(string annotation)`

Note that the first two bullets represent breaking changes.

**Comment by tgregg** [comment]
Closed via #77.
