### ISSUE TITLE
Consider dropping support for netcoreapp1.0 and netcoreapp2.0

### ISSUE THREAD

**Issue by dhhoang** [amzn/ion-dotnet#73]
Right now Amazon.IonDotnet.Tests includes test targets for `netcoreapp2.0` and `netcoreapp1.0`.
Since Microsoft's support for these runtimes has ended (see https://dotnet.microsoft.com/download/dotnet-core) perhaps we should consider dropping those?

**Comment by tgregg** [comment]
Closed via #83
