### ISSUE TITLE
Update cookbook examples to use new annotations methods

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-dotnet#85]
Specifically, use them in the Sparse Reads example in the cookbook, replacing the inline implementation that is currently there.

_As noted by @tgregg in https://github.com/amzn/ion-dotnet/issues/68#issuecomment-583176210_

**Comment by tgregg** [comment]
Closing this in favor of https://github.com/amzn/ion-docs/pull/114 , which will be merged after the next ion-dotnet release.
